-- Create feed_performance_metrics table
CREATE TABLE IF NOT EXISTS feed_performance_metrics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  view_type TEXT NOT NULL CHECK (view_type IN ('feed', 'profile')),
  request_type TEXT NOT NULL CHECK (request_type IN ('initial_load', 'load_more', 'refresh')),
  load_time_ms INTEGER NOT NULL,
  batch_size INTEGER NOT NULL,
  pagination_offset INTEGER NOT NULL DEFAULT 0,
  items_returned INTEGER NOT NULL,
  timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  platform TEXT NOT NULL,
  connection_type TEXT NOT NULL,
  device_memory FLOAT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create index on timestamp for time-based queries
CREATE INDEX IF NOT EXISTS feed_performance_metrics_timestamp_idx ON feed_performance_metrics (timestamp);

-- Create index on view_type for filtering by view
CREATE INDEX IF NOT EXISTS feed_performance_metrics_view_type_idx ON feed_performance_metrics (view_type);

-- Create index on request_type for filtering by request type
CREATE INDEX IF NOT EXISTS feed_performance_metrics_request_type_idx ON feed_performance_metrics (request_type);

-- Add RLS policies
ALTER TABLE feed_performance_metrics ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to insert metrics
CREATE POLICY "Allow authenticated users to insert feed metrics"
ON feed_performance_metrics FOR INSERT
TO authenticated
WITH CHECK (true);

-- Allow authenticated users to read metrics
CREATE POLICY "Allow authenticated users to read feed metrics"
ON feed_performance_metrics FOR SELECT
TO authenticated
USING (true);

-- Add comments
COMMENT ON TABLE feed_performance_metrics IS 'Stores performance metrics for feed and profile data requests';
COMMENT ON COLUMN feed_performance_metrics.view_type IS 'Type of view being measured (feed or profile)';
COMMENT ON COLUMN feed_performance_metrics.request_type IS 'Type of request (initial_load, load_more, refresh)';
COMMENT ON COLUMN feed_performance_metrics.load_time_ms IS 'Time taken to complete the request in milliseconds';
COMMENT ON COLUMN feed_performance_metrics.batch_size IS 'Number of items requested in this batch';
COMMENT ON COLUMN feed_performance_metrics.pagination_offset IS 'Pagination offset for this request';
COMMENT ON COLUMN feed_performance_metrics.items_returned IS 'Number of items actually returned from the request';
COMMENT ON COLUMN feed_performance_metrics.platform IS 'Platform the app is running on (web, ios, android)';
COMMENT ON COLUMN feed_performance_metrics.connection_type IS 'Network connection type (4g, 3g, etc)';
COMMENT ON COLUMN feed_performance_metrics.device_memory IS 'Available device memory in GB';
